/**
 * HackSkill Unidirectional Action Identifiers
 */

export const ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SWITCH_TAB: 'SWITCH_TAB',
  SWITCH_THEME: 'SWITCH_THEME',
  ADD_XP: 'ADD_XP',
  INCREMENT_STREAK: 'INCREMENT_STREAK',
  ADD_CERTIFICATE: 'ADD_CERTIFICATE',
  TRIGGER_EVACUATION: 'TRIGGER_EVACUATION',
  PLACE_ORDER: 'PLACE_ORDER'
};
